### ISSUE TITLE
Can't set page to the same page (but with new content)

### ISSUE THREAD

**Issue by liabru** [atotic/lazy-pages#6]
I have an issue where I need to refresh a lazy-page with new content, but I also want the page transition as if it were a new page. Currently there is [code to prevent this](https://github.com/atotic/lazy-pages/blob/master/lazy-pages.html#L483-L485) which I have not been able to get around without forking.

I don't want to have new elements for every page since they all share the same type of element and the pages are dynamic and I am using routing.

My current work around is to set the page to a 'blank' element, then quickly set the page back to the original page (inside a timeout). This mostly works, but it isn't great. I'd be grateful you could tell me a better way or if you could add support for this. Thanks.

**Comment by atotic** [comment]
You are swapping out page's content, but would like the transition? I'd make the page an animation runner, and run the transition manually when you swap the content.

**Comment by ciampo** [comment]
@atotic, then what do you suggest for handling subroutes? eg. /browse/[category]

Thanks

**Comment by atotic** [comment]
Can you give me a code example to work off?

**Comment by ciampo** [comment]
Sure. Let's say that my site has 3 pages: `home`, `browse`, `about`.

``` html
<lazy-pages
    id="pages"
    attr-for-selected="page"
    selected="{{page}}">
  <template is="dom-if" page="home" restamp>
    <x-page-home></x-page-home>
  </template>
  <template is="dom-if" page="browse" restamp>
    <x-page-browse></x-page-browse>
  </template>
  <template is="dom-if" page="about" restamp>
    <x-page-about></x-page-about>
  </template>
</lazy-pages>
```

The browse page shows all the products within a certain category. This category is reflected in the URL a as a subroute, e.g.: `site.com/browse/category1`.

Now, let's say the category changes, e.g.: `site.com/browse/category2`. The page stays the same (browse), but needs to be refreshed with the new content (and possibly with the same page transitions as everywhere else in the site).

Do you have a solution for this case? E.g. making a duplicate of the page and transitioning to it?

Thanks,
Marco

**Comment by atotic** [comment]
I would make x-page-browse responsible for handling categories. x-page-browse can have another set of lazy pages internally...

Something like that, there is no one true way to handle nesting.
