### ISSUE TITLE
height not adjusting according to the height of children

### ISSUE THREAD

**Issue by akheelkm007** [atotic/lazy-pages#9]
I want the height of the lazy-pages element adjust to the height of the it's children automatically.

Is it doing it right now? Am I doing something wrong?

**Comment by atotic** [comment]
I am not longer maintaining lazy-pages. I've seen others run into this, and figure it out.

**Comment by akheelkm007** [comment]
I'm new to Polymer. Could you point me in the right direction?

**Comment by atotic** [comment]
No.
